server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    pathType: ImplementationSpecific
    hosts:
      - demo.local
    paths:
      - /prometheus(/|$)(.*)

