# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Prima VM: master node
  config.vm.define "k8s-master" do |master|
    master.vm.box = "rockylinux/9"
    master.vm.network "private_network", ip: "192.168.168.31"
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.disksize.size = '10GB'

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

  
  end

  # Seconda VM: worker 1
  config.vm.define "k8s-worker1" do |worker1|
    worker1.vm.box = "rockylinux/9"
    worker1.vm.network "private_network", ip: "192.168.168.32"
    worker1.vm.network "forwarded_port", guest: 8082, host: 8082
    worker1.disksize.size = '10GB'

    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end


  end

  # Terza VM: worker 2
  config.vm.define "k8s-worker2" do |worker2|
    worker2.vm.box = "rockylinux/9"
    worker2.vm.network "private_network", ip: "192.168.168.33"
    worker2.vm.network "forwarded_port", guest: 8083, host: 8083
    worker2.disksize.size = '10GB'

    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

  
  end

end




