---

- name: installa jenkins
  ansible.builtin.shell: |
    sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc \
    https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null
    sudo apt-get update
    sudo apt-get install jenkins

- name: install java e fontconfig
  apt:
    name:
      - fontconfig
      - openjdk-21-jre
    state: present
    update_cache: yes
  become: yes
      
- name: start jenkins
  ansible.builtin.systemd: 
    name: jenkins
    state: started
    enabled: yes
- name: Ottieni crumb da Jenkins e salva cookie JSESSIONID
  ansible.builtin.uri:
    url: http://localhost:8080/crumbIssuer/api/json
    method: GET
    user: alessandro
    password: "{{ Token_Master }}"
    force_basic_auth: yes
    return_content: yes
    status_code: 200
  register: crumb_response

- name: Estrai JSESSIONID dal cookie (header Set-Cookie)
  set_fact:
    jenkins_cookie: "{{ crumb_response.cookies.JSESSIONID }}"

- name: Genera nuovo API token (POST con CSRF protection)
  ansible.builtin.uri:
    url: http://localhost:8080/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken
    method: POST
    user: alessandro
    password: "{{ Token_Master }}"
    force_basic_auth: yes
    headers:
      "{{ crumb_response.json.crumbRequestField }}": "{{ crumb_response.json.crumb }}"
      Content-Type: application/x-www-form-urlencoded
      Cookie: "JSESSIONID={{ jenkins_cookie }}"
    body: "newTokenName=token-da-script"
    body_format: form-urlencoded
    return_content: yes
    status_code: 200
  register: api_token_response

- name: Estrai token API dalla risposta JSON
  set_fact:
    jenkins_api_token: "{{ api_token_response.json.data.tokenValue }}"

- name: Crea nodo agente Jenkins via API con token
  ansible.builtin.uri:
    url: http://localhost:8080/computer/doCreateItem
    method: POST
    user: alessandro
    password: "{{ jenkins_api_token }}"
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ crumb_response.json.crumb }}"
      Content-Type: application/x-www-form-urlencoded
      Cookie: "JSESSIONID={{ jenkins_cookie }}"
    body_format: form-urlencoded
    body:
      name: "{{ Agent_slave_name }}"
      type: "hudson.slaves.DumbSlave"
      json: >-
        {
          "name": "{{ Agent_slave_name }}",
          "nodeDescription": "",
          "numExecutors": "1",
          "remoteFS": "/home/jenkins/agent",
          "labelString": "",
          "mode": "EXCLUSIVE"
        }
    status_code: 302
  register: create_agent_response

- name: Debug risposta creazione agente
  debug:
    var: create_agent_response.status

