---
- name: install java e fontconfig
  apt:
    name:
      - fontconfig
      - openjdk-21-jre
    state: present
    update_cache: yes
  become: yes

- name: controlla versione java
  command: java -version


- name: Scarica agent.jar da Jenkins master
  ansible.builtin.get_url:
    url: http://192.168.2.111:8080/jnlpJars/agent.jar
    dest: /home/jenkins/agent/agent.jar
    mode: '0755'

  

- name: Estrai il secret per il nodo agente usando uri
  ansible.builtin.uri:
    url: "http://192.168.2.111:8080/computer/{{ Agent_slave_name }}/jenkins-agent.jnlp"
    method: GET
    user: alessandro
    password: "{{ Token_Master }}"
    force_basic_auth: yes
    return_content: yes
  register: response

- name: Estrai il secret dal contenuto della risposta
  set_fact:
    SECRET: "{{ response.content | regex_search('<argument>([a-f0-9]{64})</argument>', '\\1') }}"


- name: debug secret
  debug:
    var: SECRET

- name: Avvia Jenkins agent con il secret ricevuto
  ansible.builtin.shell: |
    mkdir -p /home/jenkins
    echo "{{SECRET}}" > /home/jenkins/agent.secret
    java -jar /home/jenkins/agent/agent.jar -url http://192.168.2.111:8080/ -secret "{{SECRET}}"  -name "{{Agent_slave_name}}" -webSocket -workDir "/home/jenkins/agent" &