---

- name: Get Token
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  vars_files:
    - secrets.yml 
  tasks:
    - name: Ottieni access token per Microsoft Graph
      azure.azcollection.azure_rm_accesstoken_info:
        client_id: "{{client_id}}"
        secret: "{{secret}}"
        tenant: "{{tenant}}"
        subscription_id: "{{subscription_id}}"
        scopes:
          - https://management.azure.com/.default
      register: token_info

    - debug:
        msg: "{{token_info}}"

    - name: Lista risorse in rg
      uri:
        url: "https://management.azure.com/subscriptions/{{subscription_id}}/resourcegroups/formazione-sou-cloud/resources?api-version=2021-04-01"
        method: GET
        headers:
          Authorization: "Bearer {{token_info.access_token}}"
          Content-Type: "application/json"
        return_content: yes
      register: objects_list

    - debug:
        msg: "{{objects_list}}"
    

    - name: Salva il report nel filesystem condiviso con l'host
      template:
        src: ./resource_group_descrition.j2
        dest: /home/vagrant/shared/report.md


