# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |ubuntu|

  ubuntu.vm.box = "ubuntu/jammy64"

   ubuntu.vm.network "public_network", ip: "191.168.33.10"
   ubuntu.vm.provider "virtualbox" do |vb|


     vb.memory = "1024"
   end
   ubuntu.vm.synced_folder "~/Desktop/Azure-Track5/shared", "/home/vagrant/shared"
   ubuntu.vm.provision "shell", inline: <<-SHELL
   sudo apt update 
   sudo apt install python3-pip -y
   sudo pip3 install ansible
   sudo ansible-galaxy collection install azure.azcollection
   sudo pip install -r /usr/local/lib/python3.10/dist-packages/ansible_collections/azure/azcollection/requirements.txt
   sudo pip install  azure.mgmt.postgresqlflexibleservers azure.mgmt.mysqlflexibleservers azure.mgmt.resourcehealth
   SHELL
   ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.vault_password_file = "~/vault-pass.txt"

   end
    

 
end
