pipeline {
    agent any

    

    stages {
        stage('PRODUCTION') {
            when {
                expression { params.ENVIRONMENT == 'PRODUCTION' }
            }
            steps {
                echo "Sono in PRODUCTION"
            }
        }

        stage('DEVELOPMENT') {
            when {
                expression { params.ENVIRONMENT == 'DEVELOPMENT' }
            }
            steps {
                echo "Sono in DEVELOPMENT"
            }
        }
    }
}
