# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.define "rocky" do |rocky|
    # Impostiamo il box di Rocky Linux 9
    rocky.vm.box = "ubuntu/jammy64"
    
    # Configurazione della rete privata con IP statico
    rocky.vm.network "private_network", ip: "192.168.168.33"
    rocky.vm.network "forwarded_port", guest: 8080, host: 8080
    # Impostiamo la dimensione del disco con il plugin vagrant-disksize
    rocky.disksize.size = '30GB'
    
    # Configurazione del provider VirtualBox
    rocky.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Imposta la RAM a 4GB
      vb.cpus = 2         # Imposta 4 CPU
    end

    # # Provisioning con Ansible
    rocky.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.vault_password_file = "~/.vault_pass.txt"
    #   #ansible.inventory_path = "inventory.ini"  # Puoi scommentare questa riga se hai un file di inventario Ansible
    end

    # Provisioning con Shell per installare kubectl
    # rocky.vm.provision "shell", inline: <<-SHELL
    #   curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
    #   sudo install kubectl /usr/local/bin/
    # SHELL
  end
  
  config.vm.define "ubuntu" do |ubuntu|
    # Impostiamo il box di Rocky Linux 9
    ubuntu.vm.box = "ubuntu/jammy64"
    
    # Configurazione della rete privata con IP statico
    ubuntu.vm.network "private_network", ip: "192.168.168.32"
    ubuntu.vm.network "forwarded_port", guest: 8080, host: 8081
    # Impostiamo la dimensione del disco con il plugin vagrant-disksize
    ubuntu.disksize.size = '30GB'
    
    # Configurazione del provider VirtualBox
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Imposta la RAM a 4GB
      vb.cpus = 2         # Imposta 4 CPU
    end

    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.vault_password_file = "~/.vault_pass.txt"
    end
  end
end



